package club.banyuan.machine;

public enum FlowStatus {
  ROOT,
  READ_PRODUCT_INFO,
  INSERT_COIN,
  PRESS_PRODUCT_BTN,
  PRESS_RETURN_BTN,
  OPEN_SERVICE_MENU,
  ADMIN_ROOT,
  ADMIN_INSPECT_STATUS,
  ADMIN_WITHDRAW_MONEY,
  ADMIN_REFILL_PRODUCT,
  ADMIN_CHANGE_PRODUCT,
  QUIT
}
